[project]
name = "algoritms"
version = "0.1.0"
description = "Drone image batch processing alogrithms"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "ultralytics>=8.3.203",
]
